name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y expect
          npm install -g @bubblewrap/cli

      - name: Configurar Instalação automática
        run: | 
          mkdir -p ~/.bubblewrap
          
          # Decodifica a chave KEYSOTRE de Base64 e salva no caminho correto
          echo "$KEYSTORE" | base64 --decode > ~/.bubblewrap/my-release-key.keystore
          
          # Gera o arquivo de configuração para o Bubblewrap
          echo '{
            "domain": "francsilva.com.br",
            "path": "/",
            "name": "Francisco Silva App",
            "shortName": "FSilva HND",
            "packageId": "br.com.francsilva",
            "display": "standalone",
            "themeColor": "#333333",
            "navigationColor": "#333333",
            "backgroundColor": "#FFFFFF",
            "enableNotifications": false,
            "signingMode": "mine",
            "startUrl": "/",
            "fallbackType": "customtabs",
            "features": {
              "playBilling": false
            },
            "appVersion": "1.0",
            "appVersionCode": 1,
            "skipSdkPrompt": false,
            "skipSigningPrompt": false,
            "autoInstallSdk": true,
            "autoInstallJdk": true,
            "autoAcceptLicenses": true,
            "signing": {
              "keystorePath": "./my-release-key.keystore",
              "keyAlias": "'"$KEY_ALIAS"'",
              "keyPassword": "'"$KEYSTORE_PASSWORD"'",
              "storePassword": "'"$KEYSTORE_PASSWORD"'"
            }
          }' > ~/.bubblewrap/config.json

      - name: Inicializar o projeto com Bubblewrap e capturar perguntas
        run: |          
          
          expect <<EOF
          # Define o tempo limite para o script
          set timeout 600
          
          
          # Inicia o processo do Bubblewrap
          spawn bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --no-interactive
          
          # Aguarda até o processo ser iniciado e então responde às perguntas
          expect {
              "? Do you want Bubblewrap to install the JDK (recommended)?" { send "Y\r" }
              "? URL path:" { send "/\r" }
              #"Downloading" { exp_continue } 
              #"Extracting" { exp_continue } 
              timeout { exit 1 }
          }
          
          # Aguarda até o final do processo para o EOF
          expect eof
          EOF
          
          # Verifica se o arquivo foi criado
          cat twa-manifest.json || echo "Erro: twa-manifest.json não foi criado"

          
          
      - name: Verificar e instalar JDK e SDK pelo Bubblewrap
        run: |
          bubblewrap doctor

      - name: Configurar Keystore e Variáveis de Ambiente
        run: |
          echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
          chmod 600 $HOME/android.keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Construir o APK com Bubblewrap
        run: |
          bubblewrap build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          PACKAGE_NAME: com.francsilva.pwa
          DOMAIN: francsilva.com.br
          URL_PATH: /
          VERSION_CODE: 1
          VERSION_NAME: 1.0.0
          MIN_SDK_VERSION: 21
