name: Build and Sign Android App with Bubblewrap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      PACKAGE_NAME: com.francsilva.pwa
      VERSION_CODE: 1
      VERSION_NAME: 1.0.0
      MIN_SDK_VERSION: 21
      DOMAIN: francsilva.com.br
      URL_PATH: /
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Android SDK
        uses: reactivecircus/setup-android@v2
        with:
          api-level: ${{ env.MIN_SDK_VERSION }}
          build-tools: '30.0.3'

      - name: Decode and save keystore
        run: |
          echo "$KEYSTORE" | base64 --decode > my-release-key.keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Initialize Bubblewrap project
        run: |
          bubblewrap init \
            --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json \
            --no-interactive
        env:
          DOMAIN: ${{ env.DOMAIN }}
          URL_PATH: ${{ env.URL_PATH }}

      - name: Build the project
        run: bubblewrap build

      - name: Sign the APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.keystore \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEYSTORE_PASSWORD \
            app/build/outputs/bundle/release/app-release.aab $KEY_ALIAS
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Clean up
        run: rm -f my-release-key.keystore
