name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Instalar dependências
      run: |
        rm -rf .bubblewrap
        # Instalar JDK 17
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        # Instalar Android SDK
        sudo apt-get install -y android-sdk
        # Configurar Bubblewrap
        npm install -g @bubblewrap/cli
        mkdir -p ~/.bubblewrap
        echo '{
          "jdkPath": "/usr/lib/jvm/java-17-openjdk-amd64",
          "androidSdkPath": "/usr/lib/android-sdk"      
        }' > ~/.bubblewrap/config.json

    - name: Configurar Keystore e Variáveis de Ambiente
      run: |
        # Decodificar a keystore a partir da variável de ambiente KEYSTORE
        echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
        # Definir permissões adequadas para a keystore
        chmod 600 $HOME/android.keystore
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}

    - name: Atualizar o Bubblewrap
      run: npm install -g @bubblewrap/cli@latest    

    - name: Inicializar e construir o aplicativo
      run: |
        curl -o manifest.json https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json
        # Rodar bubblewrap init com o manifesto e verificar possíveis interações
        # bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --no-interactive || exit 0
        bubblewrap init --manifest file://$(pwd)/manifest.json --no-interactive
        bubblewrap build
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        PACKAGE_NAME: com.francsilva.pwa
        DOMAIN: francsilva.com.br
        URL_PATH: /
        VERSION_CODE: 1
        VERSION_NAME: 1.0.0
        MIN_SDK_VERSION: 21
