name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y expect
          npm install -g @bubblewrap/cli

      - name: Inicializar o projeto com Bubblewrap e configurar JDK/SDK usando `extract`
        run: |
          expect <<EOF
          spawn bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --packageId com.francsilva.pwa --host francsilva.com.br --name "Francisco Silva App" --launcherName "FSilva HND" --no-interactive
          
          # Espera e imprime a pergunta do SDK
          expect "? Do you want to install the Android SDK (Y/n):"
          send_user "Pergunta: Do you want to install the Android SDK (Y/n):\r\n"
          send "Y\r"
          expect "? Do you want Bubblewrap to install the JDK (recommended)?"
          send_user "Pergunta: Do you want Bubblewrap to install the JDK (recommended)?\r\n"
          send "Y\r"
          expect "? Do you want to install the default build tools (Y/n):"
          send_user "Pergunta: Do you want to install the default build tools (Y/n):\r\n"
          send "Y\r"
          expect "? Domain:"
          send_user "Pergunta: Domain:\r\n"
          send "francsilva.com.br\r"
          expect "? URL path:"
          send_user "Pergunta: URL path:\r\n"
          send "/\r"
          expect eof
          EOF

      - name: Verificar e instalar JDK e SDK pelo Bubblewrap
        run: |
          bubblewrap doctor

      - name: Configurar Keystore e Variáveis de Ambiente
        run: |
          echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
          chmod 600 $HOME/android.keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Construir o APK com Bubblewrap
        run: |
          bubblewrap build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          PACKAGE_NAME: com.francsilva.pwa
          DOMAIN: francsilva.com.br
          URL_PATH: /
          VERSION_CODE: 1
          VERSION_NAME: 1.0.0
          MIN_SDK_VERSION: 21
