name: Build APK with Bubblewrap

on:
  push:
    branches:
      - main  # ou a branch que você deseja usar
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install Bubblewrap
        run: |
          sudo apt update
          sudo apt install -y bubblewrap

      - name: Download Manifest
        run: |
          curl -o manifest.json https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json

      - name: Build APK
        run: |
          bubblewrap init --manifest=manifest.json
          bubblewrap build --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: dist/*.apk
