name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Instalar dependências
      run: |
        rm -rf .bubblewrap
        # Instalar JDK 17
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        sudo apt-get install jq # ler arquivos
        # Instalar pacotes essenciais do SDK
        sudo apt-get install -y unzip wget
        # Baixar e extrair a versão correta do Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
        rm commandlinetools-linux-8512546_latest.zip
        # Configurar o diretório correto
        mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        # Atualizar variáveis de ambiente
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        # Garantir que o sdkmanager funcione
        sdkmanager --version
        # Aceitar licenças do SDK
        yes | sdkmanager --licenses
        # Instalar plataformas e ferramentas necessárias
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        # Instalar Bubblewrap
        npm install -g @bubblewrap/cli
        mkdir -p ~/.bubblewrap
        echo '{
          "jdkPath": "/usr/lib/jvm/java-17-openjdk-amd64",
          "androidSdkPath": "'$HOME'/android-sdk"      
        }' > ~/.bubblewrap/config.json

    - name: Configurar Keystore e Variáveis de Ambiente
      run: |
        # Decodificar a keystore a partir da variável de ambiente KEYSTORE
        echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
        # Definir permissões adequadas para a keystore
        chmod 600 $HOME/android.keystore
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}

    - name: Atualizar o Bubblewrap
      run: npm install -g @bubblewrap/cli@latest    

    - name: Inicializar e construir o aplicativo
      run: |       
        sudo apt-get install -y expect
        expect <<EOF
        spawn bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --packageId com.francsilva.pwa --host francsilva.com.br --name "Francisco Silva App" --launcherName "FSilva HND" --no-interactive
        expect "? Domain:"
        send "francsilva.com.br\r"
        expect "? URL path:"
        send "/\r"
        expect eof
        EOF
        cat twa-manifest.json || echo "Erro: twa-manifest.json não foi criado"
        bubblewrap build
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        PACKAGE_NAME: com.francsilva.pwa
        DOMAIN: francsilva.com.br
        URL_PATH: /
        VERSION_CODE: 1
        VERSION_NAME: 1.0.0
        MIN_SDK_VERSION: 21
