name: Build TWA APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          npm install -g @bubblewrap/cli

      - name: Instalar Bubblewrap e aceitar licenças
        run: |
          bubblewrap doctor --install
          yes | ~/.bubblewrap/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.bubblewrap/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Baixar manifesto
        run: |
          curl -o twa-manifest.json "https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json"

      - name: Inicializar Bubblewrap sem interações
        run: |
          bubblewrap init --manifest twa-manifest.json --skipInput

      - name: Criar Keystore a partir do segredo
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > my-release-key.keystore

      - name: Build APK assinado
        run: |
          bubblewrap build --signingKeyPath my-release-key.keystore --signingKeyAlias ${{ secrets.KEY_ALIAS }} --signingKeyPassword ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload do APK assinado
        uses: actions/upload-artifact@v4
        with:
          name: TWA-APK
          path: app-release-signed.apk
