name: Build PWA APK for Google Play Store

on:
  push:
    branches:
      - main  # Isso roda o workflow sempre que houver push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Aumenta o timeout para 60 minutos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Versão 4 do checkout

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'  # Usando Node.js 17

    - name: Install Bubblewrap CLI globally
      run: |
        echo "Instalando o Bubblewrap CLI..."
        npm install -g @bubblewrap/cli  # Instalando o Bubblewrap CLI globalmente
        echo "Bubblewrap CLI instalado com sucesso."

    - name: Initialize Bubblewrap project
      run: |
        echo "Iniciando o Bubblewrap init..."
        
        # Usando `yes` para automatizar as interações com o SDK e JDK
        yes "y" | bubblewrap init --manifest=https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json | tee result.log | grep -v "yes" | grep -v "no" 
        
        echo "Bubblewrap init concluído!"

    - name: Build the APK
      run: |
        echo "Iniciando o build do APK..."
        bubblewrap build --release --sdk 17 --version 4
        echo "Build do APK concluído."

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4  # Usando a versão v4 do upload-artifact
      with:
        name: app-release.apk
        path: ./app-release.apk
