name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Pode trocar para 'ubuntu-22.04-large' se precisar de mais recursos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Check installed versions
        run: |
          java -version
          node -v
          npm -v
          bubblewrap --version

      - name: Initialize Bubblewrap
        run: |
          # Usando 'yes' para responder automaticamente todas as perguntas com "No" e "Yes"
          yes No | bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json \
            --no-interactive --skip-sdk --jdk $JAVA_HOME

      - name: Debug Disk and Processes
        run: |
          df -h
          ps aux | grep emulator

      - name: Build Bubblewrap APK
        run: |
          timeout 1800 bubblewrap build --no-interactive \
            --keystore-path gvendas.keystore \
            --key-password ${{ secrets.KEY_PASSWORD }} \
            --key-alias gvendas

      - name: Start Android Emulator
        run: |
          # Instalar as dependências necessárias
          sdkmanager "system-images;android-30;google_apis;x86_64"
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          
          # Iniciar o emulador em segundo plano
          nohup emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gvendas-apk
          path: app/build/outputs/apk/debug/app-debug.apk
