name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Instalar dependências
        run: |
          rm -rf .bubblewrap
          sudo apt-get update
          
          # Instalar JDK 17
          sudo apt-get install -y openjdk-17-jdk jq

          # Instalar Android SDK e configurar PATH
          sudo apt-get install -y android-sdk
          echo 'export ANDROID_SDK_ROOT=/usr/lib/android-sdk' >> $HOME/.bashrc
          echo 'export PATH=$PATH:/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/platform-tools:/usr/lib/android-sdk/tools/bin' >> $HOME/.bashrc
          source $HOME/.bashrc
          
          # Instalar Bubblewrap
          npm install -g @bubblewrap/cli
          mkdir -p ~/.bubblewrap
          echo '{ "jdkPath": "/usr/lib/jvm/java-17-openjdk-amd64", "androidSdkPath": "/usr/lib/android-sdk" }' > ~/.bubblewrap/config.json

      - name: Adicionar sdkmanager ao PATH
        run: |
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/platform-tools:/usr/lib/android-sdk/tools/bin
          echo "sdkmanager versão:"
          sdkmanager --version || echo "Erro ao executar sdkmanager"

      - name: Configurar Keystore e Variáveis de Ambiente
        run: |
          echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
          chmod 600 $HOME/android.keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Atualizar o Bubblewrap
        run: npm install -g @bubblewrap/cli@latest

      - name: Inicializar e construir o aplicativo
        run: |
          sudo apt-get install -y expect
          expect <<EOF
          spawn bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --packageId com.francsilva.pwa --host francsilva.com.br --name "Francisco Silva App" --launcherName "FSilva HND" --no-interactive
          expect "? Domain:"
          send "francsilva.com.br\r"
          expect "? URL path:"
          send "/\r"
          expect eof
          EOF
          cat twa-manifest.json || echo "Erro: twa-manifest.json não foi criado"
          bubblewrap build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          PACKAGE_NAME: com.francsilva.pwa
          DOMAIN: francsilva.com.br
          URL_PATH: /
          VERSION_CODE: 1
          VERSION_NAME: 1.0.0
          MIN_SDK_VERSION: 21
