name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Pode trocar para 'ubuntu-22.04-large' se precisar de mais recursos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Check installed versions
        run: |
          java -version
          node -v
          npm -v
          bubblewrap --version

      - name: Initialize Bubblewrap
        run: |
          echo "No" | bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json \
            --no-interactive --skip-sdk --jdk $JAVA_HOME

      - name: Debug Disk and Processes
        run: |
          df -h
          ps aux | grep emulator

      - name: Build Bubblewrap APK
        run: |
          timeout 1800 bubblewrap build --no-interactive \
            --keystore-path gvendas.keystore \
            --key-password ${{ secrets.KEY_PASSWORD }} \
            --key-alias gvendas

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          avd-name: test
          emulator-boot-timeout: 300
          disable-linux-hw-accel: true
          disable-animations: true
          disable-spellchecker: true
          enable-hw-keyboard: false

      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gvendas-apk
          path: app/build/outputs/apk/debug/app-debug.apk
