name: Build APK with Bubblewrap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ninja-build \
          meson \
          pkg-config \
          python3 \
          libcap-dev
        git clone https://github.com/containers/bubblewrap.git
        cd bubblewrap
        meson setup _builddir
        meson compile -C _builddir
        sudo meson install -C _builddir

    - name: Gerar APK com Bubblewrap
      run: |
        cd ..
        bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json
        bubblewrap build

    - name: Fazer upload do APK como artefato
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: path/to/your/app-release.apk
