name: Build TWA APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk curl -y
          npm install -g @bubblewrap/cli

      - name: Baixar e instalar o JDK 17 openjdk no diretório padrão do Bubblewrap
        run: |
          mkdir -p ~/.bubblewrap/jdk
          curl -L "https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz" | tar xz -C ~/.bubblewrap/jdk --strip-components=1

      - name: Instalar o Android SDK e aceitar licenças
        run: |
          # Instalar SDK no diretório padrão do Bubblewrap
          mkdir -p ~/.bubblewrap/android-sdk
          curl -L "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -o sdk-tools.zip
          unzip sdk-tools.zip -d ~/.bubblewrap/android-sdk/
          yes | ~/.bubblewrap/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.bubblewrap/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          
      - name: Baixar manifesto
        run: |
          curl -o twa-manifest.json "https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json"

      - name: Inicializar Bubblewrap sem interações
        run: |
          bubblewrap init --manifest twa-manifest.json --skipInput

      - name: Criar Keystore a partir do segredo
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > my-release-key.keystore

      - name: Build APK assinado
        run: |
          bubblewrap build --signingKeyPath my-release-key.keystore --signingKeyAlias ${{ secrets.KEY_ALIAS }} --signingKeyPassword ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload do APK assinado
        uses: actions/upload-artifact@v4
        with:
          name: TWA-APK
          path: app-release-signed.apk
