name: Build TWA APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y curl unzip git wget python3 python3-pip npm

      - name: Instalar JDK e Android SDK
        run: |
          # Criar diretório para o JDK
          mkdir -p $HOME/.bubblewrap/jdk
          cd $HOME/.bubblewrap/jdk
          
          # Baixar uma versão fixa do JDK 17
          wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.11%2B9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.11_9.tar.gz
          tar -xvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.11_9.tar.gz --strip-components=1
          rm OpenJDK17U-jdk_x64_linux_hotspot_17.0.11_9.tar.gz
          
          # Criar diretório para o Android SDK
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mv cmdline-tools latest

      - name: Configurar variáveis de ambiente
        run: |
          echo "JAVA_HOME=$HOME/.bubblewrap/jdk" >> $GITHUB_ENV
          echo "BUBBLEWRAP_JDK_PATH=$HOME/.bubblewrap/jdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/.bubblewrap/jdk/bin:$HOME/android-sdk/cmdline-tools/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/emulator:$PATH" >> $GITHUB_ENV

      - name: Aceitar licenças e instalar Build Tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Instalar Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Baixar o manifest e inicializar o Bubblewrap
        run: |
          curl -o $HOME/twa-manifest.json "https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json"
          mkdir -p $HOME/.android
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > $HOME/.android/app-signing-key.jks    
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          
          java -version
          sdkmanager --version
          
          yes | bubblewrap init --manifest $HOME/twa-manifest.json --jdkPath $HOME/.bubblewrap/jdk --sdkPath $HOME/android-sdk --skipPwaValidation

      - name: Build do APK
        run: yes | bubblewrap build

      - name: Upload do APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: APK-Gerado
          path: app-release-signed.apk
