name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Ajuste para uma versão LTS compatível com o Bubblewrap

    - name: Instalar dependências
      run: |
        npm install -g @bubblewrap/cli
        mkdir -p ~/.bubblewrap
        echo '{
          "jdkPath": "/usr/lib/jvm/java-11-openjdk-amd64",
          "androidSdkPath": "/usr/lib/android-sdk",
          "domain": "francsilva.com.br",
          "urlPath": "/",
          "manifest": "https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json"
        }' > ~/.bubblewrap/config.json

    - name: Inicializar e construir o aplicativo
      run: |
        bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --no-interactive
        bubblewrap build
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        PACKAGE_NAME: com.francsilva.pwa
        VERSION_CODE: 1
        VERSION_NAME: 1.0.0
        MIN_SDK_VERSION: 21
