name: Build and Sign Android App with Bubblewrap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      PACKAGE_NAME: com.francsilva.pwa
      VERSION_CODE: 1
      VERSION_NAME: 1.0.0
      MIN_SDK_VERSION: 21
      DOMAIN: franscilva.com.br
      URL_PATH: /

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Set up Android SDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3"
          android list targets

      - name: Decode and save keystore
        run: |
          echo "$KEYSTORE" | base64 --decode > my-release-key.keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Install Node.js and Bubblewrap
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo npm install -g @bubblewrap/cli

      - name: Initialize Bubblewrap project
        run: |
          bubblewrap init \
            --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json \
            --package-name $PACKAGE_NAME \
            --version-code $VERSION_CODE \
            --version-name $VERSION_NAME \
            --min-sdk-version $MIN_SDK_VERSION \
            --domain $DOMAIN \
            --url-path $URL_PATH \
            --no-interactive

      - name: Build the project
        run: bubblewrap build

      - name: Sign the APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.keystore \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEYSTORE_PASSWORD \
            app/build/outputs/bundle/release/app-release.aab $KEY_ALIAS
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Clean up
        run: rm -f my-release-key.keystore
