name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Instalar dependências
      run: |
        rm -rf .bubblewrap
        # Instalar JDK 17
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        sudo apt-get install -y jq # Para ler arquivos JSON
        # Remover SDK antigo e instalar cmdline-tools manualmente
        sudo apt-get remove -y android-sdk
        sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        sudo unzip cmdline-tools.zip -d /usr/lib/android-sdk/cmdline-tools
        sudo rm cmdline-tools.zip
        # Configurar Bubblewrap
        npm install -g @bubblewrap/cli
        mkdir -p ~/.bubblewrap
        echo '{
          "jdkPath": "/usr/lib/jvm/java-17-openjdk-amd64",
          "androidSdkPath": "/usr/lib/android-sdk/cmdline-tools/latest"
        }' > ~/.bubblewrap/config.json
        # Ajustar permissões do sdkmanager
        sudo chmod +x /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager
        # Aceitar licenças do Android SDK
        yes | sudo /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses


    - name: Configurar Keystore e Variáveis de Ambiente
      run: |
        # Decodificar a keystore a partir da variável de ambiente KEYSTORE
        echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
        # Definir permissões adequadas para a keystore
        chmod 600 $HOME/android.keystore
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}

    - name: Atualizar o Bubblewrap
      run: npm install -g @bubblewrap/cli@latest

    - name: Inicializar e construir o aplicativo
      run: |
        sudo apt-get install -y expect
        expect <<EOF
        spawn bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --packageId com.francsilva.pwa --host francsilva.com.br --name "Francisco Silva App" --launcherName "FSilva HND" --no-interactive
        expect "? Domain:"
        send "francsilva.com.br\r"
        expect "? URL path:"
        send "/\r"
        expect eof
        EOF
        cat twa-manifest.json || echo "Erro: twa-manifest.json não foi criado"
        bubblewrap build
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        PACKAGE_NAME: com.francsilva.pwa
        DOMAIN: francsilva.com.br
        URL_PATH: /
        VERSION_CODE: 1
        VERSION_NAME: 1.0.0
        MIN_SDK_VERSION: 21
