name: Build e Assinar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Instalar dependências
      run: |
        # Baixar e configurar a keystore
        echo "$KEYSTORE" | base64 --decode > $HOME/android.keystore
        chmod 600 $HOME/android.keystore
        # Atualizar o Bubblewrap
        npm install -g @bubblewrap/cli@latest

    - name: Configurar Keystore e Variáveis de Ambiente
      run: |
        # Definir variáveis de ambiente para a keystore
        echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $GITHUB_ENV
        echo "KEY_ALIAS=$KEY_ALIAS" >> $GITHUB_ENV
        echo "PACKAGE_NAME=com.francsilva.pwa" >> $GITHUB_ENV
        echo "DOMAIN=francsilva.com.br" >> $GITHUB_ENV
        echo "URL_PATH=/" >> $GITHUB_ENV
        echo "VERSION_CODE=1" >> $GITHUB_ENV
        echo "VERSION_NAME=1.0.0" >> $GITHUB_ENV
        echo "MIN_SDK_VERSION=21" >> $GITHUB_ENV

    - name: Inicializar e construir o aplicativo usando Docker
      run: |
        docker run --rm \
          -e KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
          -e KEY_ALIAS=$KEY_ALIAS \
          -e PACKAGE_NAME=$PACKAGE_NAME \
          -e DOMAIN=$DOMAIN \
          -e URL_PATH=$URL_PATH \
          -e VERSION_CODE=$VERSION_CODE \
          -e VERSION_NAME=$VERSION_NAME \
          -e MIN_SDK_VERSION=$MIN_SDK_VERSION \
          -v $HOME:/workspace \
          ghcr.io/googlechromelabs/bubblewrap:latest \
          /bin/sh -c "bubblewrap init --manifest https://api.gvendas.app.br/gvendas/site/3/manifest/?format=json --packageId $PACKAGE_NAME --host $DOMAIN --name 'Francisco Silva App' --launcherName 'FSilva HND' --no-interactive --url-path $URL_PATH && bubblewrap build"
